[project]
name = "nether"
description = "the foundation library"
dynamic = ["readme", "version"]
requires-python = ">=3.12"
license = {text = "MIT"}
dependencies = [
    "aiohttp",
    "pywin32", # TODO: add as extras
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
version = {attr = "nether.__init__.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[tool.pytest.ini_options]
markers = [
    "domain",
    "service",
    "storage",
]