name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - 'hotfix*'
      - 'feature*'
      - 'release*'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx HTML docs
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ARJUNA_BOT_ID }}
          private_key: ${{ secrets.ARJUNA_BOT_PRIVATE_KEY }}
          repositories: >-
            ["nether"]

      - name: Deploy to GitHub Pages (arjuna-systems)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          external_repository: arjuna-systems/nether
          publish_dir: docs/build/html
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name == 'main' && '' || github.ref_name }}
          force_orphan: false
          user_name: 'arjuna-bot[bot]'
          user_email: 'arjuna-bot[bot]@users.noreply.github.com'
