name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - 'hotfix*'
      - 'feature*'
      - 'release*'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx HTML docs
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GITHUB_APP_ID }}
          private_key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.GITHUB_INSTALLATION_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}
          force_orphan: false
